#!/usr/bin/env python3
r"""
Produce a "body-only" copy of a text corpus with references and appendices
removed, so that corpus-size and antithesis-rate comparisons aren't skewed
by back-matter that isn't subject to the venue's page limit.

Two extraction types need two different boundary-detection strategies,
because they fail in different ways:

- ACL 2019 (pdftotext from PDF): the References heading is usually present
  as literal text, but pdftotext emits a form-feed (\x0c) at each page
  break with no blank line, so the blank-line-delimited heading detector
  in split_paper_sections.py almost never matches it (under 0.2% of files). Fix:
  treat \x0c as a line break too, then look for a bare "References" /
  "Bibliography" line. Whatever follows (references + any appendix, which
  in ACL-style papers always comes after references) is dropped. 96.3%
  of ACL 2019 files have a match; the rest are left untouched (returned
  as-is, flagged not_truncated=True) rather than guessing wrong -- several
  are non-English-venue papers (clicit, ijclclp) whose back-matter heading
  isn't literally "References".

- arXiv 2026 / version-diff (detex'd LaTeX source): the References list is
  USUALLY ABSENT ALREADY, because it's generated by BibTeX from a separate
  .bib file at compile time and never appears as literal text in the .tex
  source detex reads (same reason the literal word "Abstract" never
  appears -- see split_paper_sections.py's docstring). Only 8/1841 files
  have literal reference text. Appendices, by contrast, ARE written
  directly in the .tex source and do show up -- but plain `\appendix`
  doesn't print the word "Appendix"; it just switches section numbering
  to letters, so most appendices start with a heading like "A Additional
  Results", not "Appendix" (only 237/1841 matched the literal-word
  check). Fix: reuse split_paper_sections.py's section splitter to find
  whichever of {conclusion, limitations, ethics, acknowledgments,
  author_contributions, references, appendix} starts LAST in the
  document, and drop everything after the end of that section -- this
  relies only on detecting the standard ACL back-matter sections that
  precede the appendix in reading order, not on detecting the appendix
  heading itself. Files with none of those anchors recognized are left
  untouched (not_truncated=True).

This is a heuristic, like the rest of this pipeline's text processing --
informative at corpus scale, not a per-file guarantee. Run with
--report to see the not-truncated rate before trusting the output.

Usage:
    python3 strip_backmatter.py acl2019 <in_dir> <out_dir> [--glob "*.txt"]
    python3 strip_backmatter.py arxiv   <in_dir> <out_dir> [--glob "*.txt"]
    python3 strip_backmatter.py <mode> <in_dir> <out_dir> --report-only
"""
import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from split_paper_sections import split_sections

REFERENCES_HEADING_RE = re.compile(r"^(references|reference|bibliography)\.?$", re.I)

ARXIV_ANCHOR_CATEGORIES = {
    "conclusion", "limitations", "ethics", "acknowledgments",
    "author_contributions", "references", "appendix",
}


def strip_acl2019(text):
    normalized = text.replace("\x0c", "\n")
    lines = normalized.split("\n")
    cut_at_line = None
    for i, l in enumerate(lines):
        if REFERENCES_HEADING_RE.match(l.strip()):
            cut_at_line = i
    if cut_at_line is None:
        return text, False
    # Recompute the cut offset in the ORIGINAL (non-normalized) text: since
    # \x0c -> \n is a 1-for-1 character substitution, line-start offsets in
    # `normalized` equal line-start offsets in `text`.
    char_offset = sum(len(l) + 1 for l in lines[:cut_at_line])
    return text[:char_offset], True


def strip_arxiv(text):
    sections = split_sections(text, abstract_min_chars=300)
    last_end = None
    pos = 0
    for s in sections:
        pos += len(s["text"])
        if s["category"] in ARXIV_ANCHOR_CATEGORIES:
            last_end = pos
    if last_end is None:
        return text, False
    return text[:last_end], True


STRIPPERS = {"acl2019": strip_acl2019, "arxiv": strip_arxiv}


def main():
    p = argparse.ArgumentParser()
    p.add_argument("mode", choices=STRIPPERS.keys())
    p.add_argument("in_dir")
    p.add_argument("out_dir")
    p.add_argument("--glob", default="*.txt")
    p.add_argument("--report-only", action="store_true",
                    help="don't write files, just print the truncation hit rate")
    args = p.parse_args()

    strip_fn = STRIPPERS[args.mode]
    in_dir = Path(args.in_dir)
    files = sorted(in_dir.glob(args.glob))
    if not files:
        sys.exit(f"no files matching {args.glob} under {in_dir}")

    out_dir = Path(args.out_dir)
    if not args.report_only:
        out_dir.mkdir(parents=True, exist_ok=True)

    n_truncated = 0
    chars_before = 0
    chars_after = 0
    for f in files:
        text = f.read_text(errors="replace")
        body, truncated = strip_fn(text)
        chars_before += len(text)
        chars_after += len(body)
        if truncated:
            n_truncated += 1
        if not args.report_only:
            (out_dir / f.name).write_text(body)

    print(f"{args.mode}: {len(files)} files, {n_truncated} truncated "
          f"({100*n_truncated/len(files):.1f}%)", file=sys.stderr)
    print(f"chars: {chars_before} -> {chars_after} "
          f"({100*(1 - chars_after/chars_before):.1f}% removed)", file=sys.stderr)


if __name__ == "__main__":
    main()
