#!/usr/bin/env python3
"""
Splice the authorship-guess passages (passages_public.jsonl from
authorship_passages.py) into authorship_coder.html, producing the published
page. Only the passage id and text go into the page; provenance stays out,
and the id is not displayed (it would tell fillers and calibration items
from the rest). Text is unified for display so that extraction artifacts
cannot reveal a passage's source: curly quotes become straight, stray spaces
before punctuation and empty parentheses are removed.

Usage:
    python3 build_authorship_page.py <authorship_dir> [out.html] --sheet-url URL [--sheet-token T]
"""
import argparse
import html
import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent


QUOTES = str.maketrans({"\u201c": '"', "\u201d": '"', "\u2018": "'", "\u2019": "'"})
DEFAULT_INTRO = ("Each passage is a few sentences from a research paper. Guess whether a person wrote it "
                 "or it was generated by an LLM. Go with your impression.")


def display(text):
    text = text.translate(QUOTES)
    text = re.sub(r"\(\s*\)", "", text)
    text = re.sub(r"\s+([,.;:)])", r"\1", text)
    text = re.sub(r"\(\s+", "(", text)
    return " ".join(text.split())


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("authorship_dir")
    ap.add_argument("out", nargs="?", default=str(HERE / "authorship_coder_built.html"))
    ap.add_argument("--sheet-url", required=True, help="Google Apps Script web app URL (sheet_backend.gs)")
    ap.add_argument("--sheet-token", default="rt-2026-annotate")
    ap.add_argument("--title", default="Who Wrote This")
    ap.add_argument("--intro", default=DEFAULT_INTRO, help="instructions shown before the first passage")
    args = ap.parse_args()
    passages = [{"pid": r["pid"], "text": display(r["text"])}
                for r in map(json.loads, open(Path(args.authorship_dir) / "passages_public.jsonl"))]
    template = (HERE / "authorship_coder.html").read_text()
    for ph in ("PASSAGES_PLACEHOLDER", "SHEET_PLACEHOLDER"):
        if ph not in template:
            raise SystemExit(f"template is missing {ph}")
    intro = "<p>" + DEFAULT_INTRO + "</p>"
    if intro not in template:
        raise SystemExit("template intro not found")
    page = template.replace(intro, "".join(f"<p>{html.escape(p)}</p>" for p in args.intro.split("\n\n")))
    page = page.replace("<title>Who Wrote This</title>", f"<title>{html.escape(args.title)}</title>", 1)
    page = page.replace("PASSAGES_PLACEHOLDER", json.dumps(passages))
    page = page.replace("SHEET_PLACEHOLDER", "  const SHEET_URL = " + json.dumps(args.sheet_url) +
                        "; const SHEET_TOKEN = " + json.dumps(args.sheet_token) + ";")
    Path(args.out).write_text(page)
    print(f"wrote {args.out} ({len(passages)} passages)")


if __name__ == "__main__":
    main()
